# Generated by Django 4.2.5 on 2023-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Название чата', 'verbose_name_plural': 'Названия чатов'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URI'),
        ),
    ]
